"use strict";
var no = 5.25+5;
//console.log("The value",no);
console.log("Type",typeof no);
console.log("Type",typeof(no));
var str = '"India is great"';
var str1 = `Value is six
seven: ${4+5+6} eight : ${no}`;
console.log(str);
console.log("Value is"+str+typeof(str));
//console.log("Type",typeof(str));
//console.log("Type"+str1+"More string Here");
console.log("Value is"+str1+typeof(str1));
console.clear();
console.log(-Infinity);
console.log(typeof Infinity);
console.log("-121/0");
console.log("Hello"/89);
console.clear();
var flag = 10>5;
console.log(flag);
console.log(typeof flag);
console.clear();
var variable;
console.log(variable);
console.log(typeof variable);
var variable = null;
console.log(variable);
console.log(typeof variable);
